version: '3.8'
services:
  # add the mariadb service
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "33062:3306"
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: password
  
  # Optional GUI for mariadb
  adminer:
    image: adminer
    container_name: mariadb_adminer
    restart: unless-stopped
    ports:
      - 8080:8080

# To use the CLI to access mariadb directly execute the following:
# docker exec -it mariadb mysql --user=root --password=password

# Login details for the mariadb GUI localhost:8080:
# Server = name of the mariadb container. "mariadb" in my case.
# Username = root
# Password = password (same as the password mentioned above)
